In [220]:
# disregard - numpy testing and initial attempt to make a cost function

#xor
training = [[0, 0], [1, 0], [0, 1], [1, 1]]
results = [0, 1, 1, 0]

weights1 = np.random.uniform(low=-1, high=1, size=(3, 2))  # looks like its 3 rows and 2 columns
weights2 = np.random.uniform(low=-1, high=1, size=(1, 2))  

bias1 = np.random.uniform(low=-1, high=1, size=3)
bias2 = np.random.uniform(low=-1, high=1, size=1)
print("weights1:        ",weights1)
print("weights1.size:    ",weights1.size)   # the total number of elements in all rows and columns
print("weights1.shape:   ",weights1.shape)  # returns a tuple that with number of rows, cols, etc... up to rank of 
print("weights1.T.shape: ",weights1.T.shape)

# bias is a one dimentional vector
#could use a Nx1 matrix or a N vector  pick whichever is easier when implementing
print("bias1:        ",bias1)
print("bias1.size:   ",bias1.size)
print("bias1.shape   ",bias1.shape)
print("bias1.T:      ",bias1.T    )  #transpose?  will it do anything to the actual 1D vector?
print("bias1.T.shape ",bias1.T.shape)  #shape still (N,)
print("bias dot bias ", np.dot(bias1,bias1))   # works fine without having to take transpose

z1 = np.dot(weights1, training[0]) + bias1
print("z1 shape ",z1.shape," contents:" ,z1)


print("test of forward for training sample 0: ", z1)
layer1 = sigmoid(z1)
    

def feed_forward(weights,inputs):
    # have a matrix for weights that's NxH (HxN)? where N is number of inputs and H is number of hidden nodes
    # result of this function is matrix multiplying the weights by the input 

def sigmoid(x, derivative=False):
  return (x*(1-x)) if derivative else 1/(1+np.exp(-x))

weights1 = np.random.uniform(low=-1, high=1, size=(16,16))
z1 = np.dot(weights1, top_training[0])
layer1 = np.maximum(z1, 0)
layer1 = sigmoid(z1)

#print(layer1)

weights2 = np.random.uniform(low=-1, high=1, size=(2,16))
z2 = np.dot(weights2, layer1)
print(z2)

layer2 = np.maximum(z2, 0)
layer2 = sigmoid(z2)

print(layer2)
y = np.zeros((2, 1))
y[0,0] = 1
print(-y)
def cost_function(v, y):
    c = (np.dot((v -y).T, v - y))
    print('c:', c)
    
cost_function(layer2, y)





[[ 1.99638755]
 [-2.29043125]]
[[0.88041727]
 [0.09191855]]
[[-1.]
 [-0.]]
c: [[0.02274905]]


In [316]:
#xor
#  note that this section is incomplete, got stuck with an operation in numpy,  ran into some weirdness
#  eventually figured out that changing '*' to np.multiply let things work for shapes (3,1)  i.e. 2d, but only 1 wide
#  this section was suspended in favor of the implementation further down the page that sucessfully learns xor

training = [[0, 0], [1, 0], [0, 1], [1, 1]]
results = [[0], [1], [1], [0]]

weights1 = np.random.uniform(low=-1, high=1, size=(3, 2))  # looks like its 3 rows and 2 colums (am i correct on this?)
weights2 = np.random.uniform(low=-1, high=1, size=(1, 3))  

bias1 = np.random.uniform(low=-1, high=1, size=(3, 1))
bias2 = np.random.uniform(low=-1, high=1, size=(1, 1))

z1 = np.dot(weights1, np.matrix(training[0]).T) + bias1
layer1 = sigmoid(z1)
print("pre-sigmoid z1", z1)
print("layer 1", layer1)
z2 = np.dot(weights2, z1) + bias2
layer2 = sigmoid(z2)
print("test of forward for training sample 0 output: ", layer2)

er_out = layer2 - results[0]
print("error:", er_out)

er2 = sigmoid(layer2,True) * er_out  # elementwise multiply with error in output   propogates backward

print("er2:",er2)

er1 = np.dot(weights2.T,er2)  # keep it as a column v

print("er1 on right side of sigmoid",er1)
print("weights1",weights1)
print("sig weights to test on a matrix ", sigmoid(weights1,True))
#print("test sig er1  ", sigmoid(er1,True))

print("layer1",layer1)
print("1-layer1",1-layer1)
print("layer1*layer1",np.multiply(layer1 , layer1))
print("layer1*(1-layer1)",layer1 * (1-layer1))
print("sigmoid(layer1,false)",sigmoid(layer1,False))
print("sigmoid(layer1,true)",sigmoid(layer1,True))

er1s = sigmoid(layer1,True) * er1
print("er1 pre sigmoid", er1s)

def cost_function(v, y):
    c = (np.dot((v -y).T, v - y))
    print('c:', c[0,0])
    
#cost_function(layer2, results[0])


pre-sigmoid z1 [[-0.91435311]
 [ 0.82106279]
 [ 0.73319569]]
layer 1 [[0.28610988]
 [0.69446189]
 [0.67550615]]
test of forward for training sample 0 output:  [[0.50712605]]
error: [[0.50712605]]
er2: [[0.12675576]]
er1 on right side of sigmoid [[ 0.11724132]
 [-0.04222791]
 [ 0.02569585]]
weights1 [[-0.55846779 -0.56347274]
 [ 0.06770019  0.80640194]
 [-0.1061895   0.70429601]]
sig weights to test on a matrix  [[-0.87035405 -0.88097427]
 [ 0.06311688  0.15611785]
 [-0.11746571  0.20826314]]
layer1 [[0.28610988]
 [0.69446189]
 [0.67550615]]
1-layer1 [[0.71389012]
 [0.30553811]
 [0.32449385]]
layer1*layer1 [[0.08185886]
 [0.48227732]
 [0.45630856]]


ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

In [273]:
#single dimensional simple example of iterative improvement of our 1x1 weight w

import math

inputs   = [ 0, .1 , .2 , .3,  -.1 , -.2 , -.3 ]
expected = [ 0, .3 , .6 , .96 , -.3 , -.6 , -.92 ]
w= .7
alpha = 0.01  # learning rate  small enough to not diverge

def forward(x):
    global w
    return w * x

def train_sample(x, p):
    global w
    global alpha
    y = forward(x)
    e = y - p
    w -= x * e * alpha 
    
def rms():  # root mean square error (the error that will be minimized by gradient descent)
    s=0
    for i in range(len(inputs)):
        e=forward(inputs[i])-expected[i]
        s+= e*e;
    return math.sqrt(s/len(inputs))  #  
        

    
def train_batch():
    global w
    for k in range(10):
        for j in range(200):
            for i in range(len(inputs)):
                train_sample(inputs[i], expected[i])
        print("new weight is: ", w, "  with rms:" ,rms())
        
        
train_batch()


new weight is:  1.723239872027639   with rms: 0.2730036852103631
new weight is:  2.3076091518999435   with rms: 0.1565102392533395
new weight is:  2.641340728037396   with rms: 0.09042270384646102
new weight is:  2.8319338491123545   with rms: 0.05342032778337136
new weight is:  2.9407810197083166   with rms: 0.03343317340927186
new weight is:  3.0029433185359276   with rms: 0.02348600308085217
new weight is:  3.0384440244741358   with rms: 0.01915542023336074
new weight is:  3.058718373169081   with rms: 0.01751291501075985
new weight is:  3.070296994048332   with rms: 0.01694280778680697
new weight is:  3.0769095103605837   with rms: 0.016752670926432282


In [276]:
# multidimensional test with no hidden layers

import math
import numpy as np

actual = np.array([[-1,1],[-1,-1]])
print("secret hidden thing that we are trying to learn is a matrix", actual.shape, " values:  ",actual)

weights = np.random.uniform(low=-1, high=1, size=(2, 2))
print("our starting random guess at our weights:",weights)


alpha = 0.01  # learning rate  small enough to not diverge

def forward(x):
    global weights
    return np.matmul(weights, x)

def train_sample(x, p):
    global weights
    global alpha
    y = forward(x)
    e = y - p
    weights = weights - np.outer(e , x ) * alpha        

    
def train_batch():
    for k in range(10):
        for j in range(200):
            x = np.random.uniform(low=-1, high=1, size=(2,))
            p= np.matmul(actual, x)
            train_sample(x,p)
        print("new weight is: ", weights)
        
        
train_batch()


secret hidden thing that we are trying to learn is a matrix (2, 2)  values:   [[-1  1]
 [-1 -1]]
our starting random guess at our weights: [[-0.39994677  0.04331311]
 [ 0.01494271  0.48366034]]
new weight is:  [[-0.68918556  0.53843479]
 [-0.44345828 -0.26172642]]
new weight is:  [[-0.82559289  0.75704504]
 [-0.69993639 -0.61907099]]
new weight is:  [[-0.92223028  0.88029464]
 [-0.82366027 -0.78166408]]
new weight is:  [[-0.95807754  0.92967197]
 [-0.90835308 -0.87494911]]
new weight is:  [[-0.97590999  0.96040664]
 [-0.95588819 -0.93486621]]
new weight is:  [[-0.98739715  0.98138109]
 [-0.97692236 -0.96929588]]
new weight is:  [[-0.99458297  0.99032961]
 [-0.98894398 -0.98343913]]
new weight is:  [[-0.99695438  0.99498542]
 [-0.99458289 -0.99188144]]
new weight is:  [[-0.99824216  0.99737769]
 [-0.99737432 -0.99605798]]
new weight is:  [[-0.99922765  0.99869801]
 [-0.99856731 -0.99784814]]


In [293]:
# test where one weight matrix is known and one isn't (so it has to be adjusted)

import math
import numpy as np

actual = np.array([[-1,1],[-1,-1]])
print("secret hidden thing that we are trying to learn is a matrix", actual.shape, " values:  ",actual)

weights1 = np.random.uniform(low=-1, high=1, size=(2, 2))
print("our starting random guess at our weights:",weights1)

weights2 = np.array([[0.5,-2],[0.5,-1]])
print("second layer of weights that we already know: ", weights2.shape, " values:  ",weights2)


alpha = 0.01  # learning rate small enough to not diverge

def forward(x):
    out1 = np.matmul(weights1, x) #after first set of weights applied
    return np.matmul(weights2, out1)

def train_sample(x, p):
    global weights1
    global alpha
    y = forward(x)
    e = y - p
    e1 = np.matmul(e,weights2) #derivative of weights2 times x is just weights2
    weights1 = weights1 - np.outer(e1 , x) * alpha 
        
    
def train_batch():
    for k in range(10):
        for j in range(2000):
            x = np.random.uniform(low=-1, high=1, size=(2,))
            p1 = np.matmul(actual, x)
            p2 = np.matmul(weights2, p1)
            train_sample(x,p2)
        print("new weights1 is: ", weights1)
        
        
train_batch()

secret hidden thing that we are trying to learn is a matrix (2, 2)  values:   [[-1  1]
 [-1 -1]]
our starting random guess at our weights: [[ 8.73410442e-01 -6.62349523e-04]
 [ 2.78908292e-01 -2.83739673e-01]]
second layer of weights that we already know:  (2, 2)  values:   [[ 0.5 -2. ]
 [ 0.5 -1. ]]
new weights1 is:  [[ 0.52137448  0.45236998]
 [-0.53936487 -1.16580903]]
new weights1 is:  [[ 0.10707745  0.6121484 ]
 [-0.66480392 -1.11743202]]
new weights1 is:  [[-0.18310284  0.70802608]
 [-0.75266344 -1.08840259]]
new weights1 is:  [[-0.39642722  0.78668819]
 [-0.81725287 -1.06458562]]
new weights1 is:  [[-0.55734467  0.84313484]
 [-0.86597475 -1.04749495]]
new weights1 is:  [[-0.66817876  0.88310188]
 [-0.89953261 -1.0353939 ]]
new weights1 is:  [[-0.75654606  0.91195678]
 [-0.92628808 -1.02665734]]
new weights1 is:  [[-0.82050231  0.93674543]
 [-0.94565247 -1.01915194]]
new weights1 is:  [[-0.86744607  0.9524128 ]
 [-0.9598659  -1.01440824]]
new weights1 is:  [[-0.90180395  0.964690

In [321]:
# 3 - 4 - 4
# 2nd layer is still locked (unchanging), 
# added a sigmoid layer between the two fully connected layers
# note that more training time is required to converge
# or learning rate, alpha, could be increased (from 0.01 to 0.1)
#

def sigmoid(x, derivative=False):
  return (np.multiply(x,(1-x))) if derivative else 1/(1+np.exp(-x))

import math
import numpy as np

actual = np.random.uniform(low=-1, high=1, size=(4, 3))
print("secret hidden thing that we are trying to learn is a matrix", actual.shape, " values:  ",actual)

weights1 = np.random.uniform(low=-1, high=1, size=(4, 3))
print("our starting random guess at our weights:",weights1)

weights2 = np.random.uniform(low=-1, high=1, size=(4, 4))
print("second layer of weights that we already know: ", weights2.shape, " values:  ",weights2)

out1 = 0
out2 = 0


alpha = 0.1  # learning rate small enough to not diverge
#might need to normalize data so this isn't too big

def forward(x):
    global out1, out2 # need to keep these global since they are used for backprop
    out1 = np.matmul(weights1, x) #after first set of weights applied
    out2 = sigmoid(out1)
    return np.matmul(weights2, out2)

def train_sample(x, p):
    global weights1
    global alpha
    y = forward(x)
    e = y - p
    e2 = np.matmul(e, weights2) #derivative of weights2 times x is just weights2
    e1 = np.multiply(e2,sigmoid(out2, True))
    weights1 = weights1 - np.outer(e1 , x) * alpha 
    
def rms():  # root mean square error (the error that will be minimized by gradient descent)
    s=0
    for i in range(len(inputs)):
        e=forward(inputs[i])-expected[i]
        s+= e*e;
    return math.sqrt(s/len(inputs))  #  
        

    
def train_batch():
    for k in range(10):
        for j in range(20000):
            x = np.random.uniform(low=-1, high=1, size=(3,))
            p1 = np.matmul(actual, x)
            p2 = sigmoid(p1)
            p3 = np.matmul(weights2, p2)
            train_sample(x,p3)
        print("new weights1-actual is: ", weights1-actual)
        
        
train_batch()

secret hidden thing that we are trying to learn is a matrix (4, 3)  values:   [[-0.90397983 -0.61630678  0.13581379]
 [ 0.99052838  0.35368045 -0.54716969]
 [ 0.94569683 -0.48596754 -0.6675901 ]
 [-0.91770213 -0.87955419 -0.33859548]]
our starting random guess at our weights: [[ 0.08653376  0.2502532  -0.52304101]
 [-0.87028645  0.94557717 -0.72706043]
 [-0.70264222  0.70918523  0.26488839]
 [-0.05445232  0.20887784  0.5895079 ]]
second layer of weights that we already know:  (4, 4)  values:   [[ 0.821859   -0.61120305 -0.07763283 -0.63417268]
 [ 0.84887314 -0.9439364   0.71505067 -0.6764717 ]
 [ 0.12034138  0.56166452  0.83373274  0.77928986]
 [-0.33154084  0.07462603 -0.08422212  0.76383978]]
new weights1-actual is:  [[ 0.01592282  0.01033042 -0.00646391]
 [ 0.00583872  0.00366667 -0.00344019]
 [-0.00948142 -0.00449051  0.00457553]
 [ 0.00706919  0.00465002 -0.00159184]]
new weights1-actual is:  [[ 3.64807000e-04  2.47178855e-04 -1.21944452e-04]
 [ 1.50388868e-04  9.51682234e-05 -7.2

In [313]:
x = np.random.uniform(low=-1, high=1, size=(1,3))
print(x)
print(1 - x)
print(x * (1-x))

[[-0.54655761  0.71660454  0.83936672]]
[[1.54655761 0.28339546 0.16063328]]
[[-0.84528283  0.20308247  0.13483023]]


In [331]:
# 2 -3- 2
# 2nd layer is unknown and must be learned.   not locked
# this  now has all the ingredients of a a neural network with input, output and a hidden layer
# only using sigmoid after the first fully connected layer, not at the end after 2nd fully connected 
#

def sigmoid(x, derivative=False):
  return (np.multiply(x,(1-x))) if derivative else 1/(1+np.exp(-x))

import math
import numpy as np

actual = np.random.uniform(low=-1, high=1, size=(3, 2))
print("secret hidden thing that we are trying to learn is a matrix", actual.shape, " values:  ",actual)

actual2 = np.random.uniform(low=-1,high=1,size=(2,3))

weights1 = np.random.uniform(low=-1, high=1, size=(3, 2))
print("our starting random guess at our weights:",weights1)

weights2 = np.random.uniform(low=-1, high=1, size=(2, 3))
print("second layer of weights that we also have to learn know: ", weights2.shape, " values:  ",weights2)

out1 = 0
out2 = 0


alpha = 0.025  # learning rate small enough to not diverge
#might need to normalize data so this isn't too big

def forward(x):
    global out1, out2
    out1 = np.matmul(weights1, x) #after first set of weights applied
    out2 = sigmoid(out1)
    return np.matmul(weights2, out2)

def train_sample(x, p):
    global weights1, weights2
    global alpha
    y = forward(x)
    e = y - p
    e2 = np.matmul(e, weights2) #derivative of weights2 times x is just weights2
    e1 = np.multiply(e2,sigmoid(out2, True))
    weights2 = weights2 - np.outer(e, out2) * alpha
    weights1 = weights1 - np.outer(e1 , x) * alpha 
    return np.dot(e,e)
    
def rms():  # root mean square error (the error that will be minimized by gradient descent)
    s=0
    for i in range(len(inputs)):
        e=forward(inputs[i])-expected[i]
        s+= e*e;
    return math.sqrt(s/len(inputs))  #  
        

    
def train_batch():
    batchsize = 50000
    for k in range(30):
        sse=0
        for j in range(batchsize):
            x = np.random.uniform(low=-1, high=1, size=(2,))
            p1 = np.matmul(actual, x)
            p2 = sigmoid(p1)
            p3 = np.matmul(actual2, p2)
            sse += train_sample(x,p3)
        print("rmse: ",math.sqrt(sse/batchsize))
        #print("new weights1-actual is: ", weights1-actual)
        #print("new weights2-actual2 is: ", weights2-actual2)
        
        
train_batch()

secret hidden thing that we are trying to learn is a matrix (3, 2)  values:   [[ 0.97449584 -0.68847914]
 [-0.38264094 -0.60920227]
 [ 0.09154447  0.34960532]]
our starting random guess at our weights: [[ 0.999307   -0.97004213]
 [ 0.33663918  0.34674273]
 [-0.90668574 -0.68351756]]
second layer of weights that we also have to learn know:  (2, 3)  values:   [[-0.60020535 -0.62542887 -0.17848813]
 [-0.66861081 -0.7604566   0.365913  ]]
rmse:  0.03945318498554707
rmse:  0.00212229097305698
rmse:  0.002033862912913282
rmse:  0.001944997874242392
rmse:  0.001861638336127047
rmse:  0.0017747907140690602
rmse:  0.0017214911833457415
rmse:  0.001655888434810225
rmse:  0.0015950831045763048
rmse:  0.0015445932715550288
rmse:  0.0014975651694478528
rmse:  0.0014522639346611257
rmse:  0.001410290770220825
rmse:  0.0013815672349808612
rmse:  0.0013504573729499966
rmse:  0.0013226426501054774
rmse:  0.001294965625810375
rmse:  0.0012714871564854788
rmse:  0.001257357480905463
rmse:  0.001238512080

In [332]:
print("new weights1-actual is: ", weights1-actual)
print("new weights2-actual2 is: ", weights2-actual2)
     
#not exactly the same

new weights1-actual is:  [[ 0.24545558 -0.21447961]
 [ 0.91087338  1.05619956]
 [-0.72683636 -0.66523868]]
new weights2-actual2 is:  [[ 0.41494286 -1.12372336  0.70877438]
 [-0.04375892  0.3780882  -0.33421679]]


In [3]:
# 2 -3- 1  (2 inputs, 3 hidden nodes, 1 output node)
# xor  classic example of training a neural network to learn the exclusive-or function
# note that xor is non-linear and thus cannot be done with only a single layer nor without any activation (sigmoid) layers

import math
import numpy as np

def sigmoid(x, derivative=False):
  return (np.multiply(x,(1-x))) if derivative else 1/(1+np.exp(-x))

#xor
training = [[0, 0], [1, 0], [0, 1], [1, 1]]
results = [0, 1, 1, 0]   

weights1 = np.random.uniform(low=-1, high=1, size=(3, 2))
print("our starting random guess at our weights:",weights1)

weights2 = np.random.uniform(low=-1, high=1, size=(1, 3))
print("second layer of weights that we also have to learn know: ", weights2.shape, " values:  ",weights2)

out1 = 0
out2 = 0


alpha = 0.025  # learning rate small enough to not diverge

def forward(x):
    global out1, out2
    out1 = np.matmul(weights1, x) #after first set of weights applied
    out2 = sigmoid(out1)
    return np.matmul(weights2, out2)

def train_sample(x, p):
    global weights1, weights2
    global alpha
    y = forward(x)
    e = y - p
    e2 = np.matmul(e, weights2) #derivative of weights2 times x is just weights2
    e1 = np.multiply(e2,sigmoid(out2, True)) #derivative of sigmoid uses the y as the input
    weights2 = weights2 - np.outer(e, out2) * alpha # out2 is global from the feed forward
    weights1 = weights1 - np.outer(e1 , x) * alpha 
    return np.dot(e,e) #return the error for this sample
    
    
def train_batch():    
    batchsize = 5000
    for k in range(10):
        sse=0
        for j in range(batchsize):
            for i in range(len(training)):
                x = training[i]
                p = [results[i]]
                sse += train_sample(x,p)
        print("rmse: ", math.sqrt(sse/batchsize))
        #print("new weights1-actual is: ", weights1-actual)
        #print("new weights2-actual2 is: ", weights2-actual2)
     
      
train_batch()
print("new weights1 is: ", weights1)
print("new weights2 is: ", weights2)

for x in training:
    print(x)
    print('feed-forward for input: ', x,' result: ', forward(x))


our starting random guess at our weights: [[-0.84641648  0.88176502]
 [-0.49487212  0.12773519]
 [-0.46190939 -0.4921082 ]]
second layer of weights that we also have to learn know:  (1, 3)  values:   [[ 0.19911986 -0.6669408   0.65966623]]
rmse:  0.8634098344491802
rmse:  0.14485350042314146
rmse:  0.07182242134494259
rmse:  0.05374436380615415
rmse:  0.04439602562924932
rmse:  0.03842183772964676
rmse:  0.03416851313067495
rmse:  0.030931879530190477
rmse:  0.028354327781020032
rmse:  0.026232420653636214
new weights1 is:  [[-5.18005722  0.3517591 ]
 [-3.23767606 -3.07491984]
 [ 0.18269852 -4.99468673]]
new weights2 is:  [[ 1.98493586 -4.07792348  2.0936063 ]]
[0, 0]
feed-forward for input:  [0, 0]  result:  [0.00030934]
[1, 0]
feed-forward for input:  [1, 0]  result:  [0.99923842]
[0, 1]
feed-forward for input:  [0, 1]  result:  [0.9992757]
[1, 1]
feed-forward for input:  [1, 1]  result:  [0.02525972]


In [ ]:
# attempted to make a 16 pixel input, hidden layer, and then 1 bit output. 
# If the image has dark pixels in the upper half, it is classified as a 1. 
# If it has dark pixels in the lower half it is a 0
# gave up this since it's way to slow although it did compile!

import numpy as np
import random
import math
# 16 pixels long

training = []
for i in range(50):
    v = np.zeros(16)
    for j in range(random.randint(1, 4)): #add up to 4 pixels
        index = random.randint(1, 7)
        v[index] = 1
    training.append(v)

for i in range(50):
    v = np.zeros(16)
    for j in range(random.randint(1, 4)): #add up to 4 pixels
        index = random.randint(8, 15)
        v[index] = 1
    training.append(v)

# 1 for top, 0 for bottom
results = np.zeros(100)
results[50:] = 1

def sigmoid(x, derivative=False):
  return (np.multiply(x,(1-x))) if derivative else 1/(1+np.exp(-x))

weights1 = np.random.uniform(low=-1, high=1, size=(16, 16))
#print("our starting random guess at our weights:",weights1)

weights2 = np.random.uniform(low=-1, high=1, size=(1, 16))
#print("second layer of weights that we also have to learn know: ", weights2.shape, " values:  ",weights2)

out1 = 0
out2 = 0


alpha = 0.025  # learning rate small enough to not diverge
#might need to normalize data so this isn't too big

def forward(x):
    global out1, out2
    out1 = np.matmul(weights1, x) #after first set of weights applied
    out2 = sigmoid(out1)
    return np.matmul(weights2, out2)

def train_sample(x, p):
    global weights1, weights2
    global alpha
    y = forward(x)
    e = y - p
    e2 = np.matmul(e, weights2) #derivative of weights2 times x is just weights2
    e1 = np.multiply(e2,sigmoid(out2, True))
    weights2 = weights2 - np.outer(e, out2) * alpha
    weights1 = weights1 - np.outer(e1 , x) * alpha 
    return np.dot(e,e)
    
    
def train_batch():
    batchsize = 5000
    for k in range(10):
        sse=0
        for j in range(batchsize):
            for i in range(len(training)):
                x = training[i]
                p = [results[i]]
                sse += train_sample(x,p)
        print("rmse: ", math.sqrt(sse/batchsize))
        #print("new weights1-actual is: ", weights1-actual)
        #print("new weights2-actual2 is: ", weights2-actual2)
        
        
train_batch()
print("new weights1 is: ", weights1)
print("new weights2 is: ", weights2)

for x in training:
    print('feed-forward for input: ', x,' result: ', forward(x))
